prewd <- getwd()
setwd("/Users/yutakashino/Dropbox/sandboxDrop/@IT/sandbox/sep2/docs")
data <- read.csv("http://spreadsheets.google.com/pub?key=0AlBuJgqcP5f3dExEQkZfem1MeXFPZTA1UUVaVVZud3c&hl=en&output=csv", header=TRUE, skip=1)
data$yearmonth <- paste(data$yearmonth, "/01", sep="")
data$yearmonth <- as.Date(data$yearmonth, "%Y/%m/%d")
library(ggplot2)
f <- ggplot(data = data, aes(x=yearmonth, y=1/stfx*100)) + geom_line(aes(colour="JPY")) + geom_hline(yintercept=1) + xlab("Year") + ylab("Effective exchange rate index") + opts(title="Effective exchange rate index JPY")  + scale_colour_manual(values=c("JPY"="darkblue"))
ggsave("japanfx2.png", plot = f)
setwd(prewd)