#setwd("/Users/yutakashino/Dropbox/sandboxDrop/@IT/sandbox/sep29/codes/")
#gtemp <- read.csv(file="nasagistemp.csv", header = T, skip = 1, sep = ',')
gtemp <- read.csv("http://spreadsheets.google.com/pub?key=0AlBuJgqcP5f3dHVCYm5SZUY4cDN1VFFMeWNKQ3IxbFE&hl=en&output=csv", header = T, skip = 1, sep = ',')
names(gtemp) <- c("i", "j", "lon", "lat", "anom")
gtemp$anom[grep(9999.00, gtemp$anom, fixed=T)] <- NA
summary(gtemp)
library(sp)
coordinates(gtemp) = c("lon", "lat")
summary(gtemp)
gridded(gtemp) <- TRUE
summary(gtemp)
png(file="grobalSummerAnomaly.png")
library(maptools)
data(wrld_simpl)
plot(wrld_simpl, add = T)

anomimage <- as.image.SpatialGridDataFrame(gtemp["anom"])
library(fields)
image.plot(anomimage, nlevel=24)
library(maptools)
data(wrld_simpl)
plot(wrld_simpl, add = T)
grid(col = "grey", lty = 1)
dev.off()