library(twitteR)
sess <- initSession('yutakashino','iamthet1!')
search1 <- searchTwitter("素敵", n = 100, session)
search2 <- searchTwitter("ステキ", n = 100, session)
tweet1 <- sapply(search1, text)
tweet2 <- sapply(search2, text)
head(tweet1)
tdf1 <- data.frame(tweet = tweet1)
tdf2 <- data.frame(tweet = tweet2) 
library(RMeCab)
RMeCabDF(tdf1, 1)
summary(sapply(RMeCabDF(tdf1, 1), length))
summary(sapply(RMeCabDF(tdf2, 1), length))